### PR TITLE
Support python3

### PR DESCRIPTION
**Pull request by mattnibs**
Whipped up this to get it working with python3. Currently passing all unit tests. I haven't tested backwards compatibility with python2- any help on that would be much appreciated.

For issue #3

### CODE REVIEW

**Comment by pawl** [comment]
I'm having trouble getting this to install on my mac and on an alpine docker image. I have libuuid installed on both.

Here's the error I'm seeing in alpine:
```
Installing collected packages: python-libuuid
  Running setup.py develop for python-libuuid
    Complete output from command /usr/local/bin/python3.4 -c "import setuptools, tokenize;__file__='/python-libuuid-py3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    building without Cython
    running develop
    running egg_info
    writing top-level names to python_libuuid.egg-info/top_level.txt
    writing dependency_links to python_libuuid.egg-info/dependency_links.txt
    writing python_libuuid.egg-info/PKG-INFO
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'python_libuuid.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'MANIFEST'
    warning: no files found matching '_uuid.c' under directory 'libuuid'
    writing manifest file 'python_libuuid.egg-info/SOURCES.txt'
    running build_ext
    building 'libuuid._uuid' extension
    gcc -Wno-unused-result -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include/python3.4m -c libuuid/_uuid.c -o build/temp.linux-x86_64-3.4/libuuid/_uuid.o
    gcc: error: libuuid/_uuid.c: No such file or directory
    gcc: fatal error: no input files
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```

Main error seems like it's: `gcc: error: libuuid/_uuid.c: No such file or directory`

**Comment by pawl** [comment]
Nevermind, looks like I need to figure out how to get `python setup.py build` working. I was previously pip installing and didn't need to worry about building. So it's not a problem with this branch.

**Comment by pawl** [comment]
Turns out I just needed to `pip install cython`

**Comment by kyoung** [comment]
+1 this would be great to get merged

**Comment by brandond** [comment]
Anyone awake over here? @dln are you still maintaining this project?

**Pull request closed without merging**
